# Generated by Django 5.2 on 2025-04-10 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("condominios", "0006_visitante"),
    ]

    operations = [
        migrations.CreateModel(
            name="ControleAcesso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("morador", "Morador"),
                            ("visitante", "Visitante"),
                            ("prestador", "Prestador"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data_entrada", models.DateTimeField(auto_now_add=True)),
                ("data_saida", models.DateTimeField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "morador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="condominios.morador",
                    ),
                ),
                (
                    "prestador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="condominios.prestador",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="condominios.unidade",
                    ),
                ),
                (
                    "visitante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="condominios.visitante",
                    ),
                ),
            ],
        ),
    ]
