# Generated by Django 5.2 on 2025-04-10 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("condominios", "0012_aviso"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Manutencao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("descricao", models.TextField()),
                ("data_inicio", models.DateTimeField()),
                ("data_fim", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planejada", "Planejada"),
                            ("em_andamento", "Em andamento"),
                            ("concluida", "Concluída"),
                        ],
                        default="planejada",
                        max_length=20,
                    ),
                ),
                (
                    "condominio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="condominios.condominio",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
