# Generated by Django 5.2 on 2025-04-11 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("condominios", "0015_comprovantepagamento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutorizacaoEntrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_visitante", models.CharField(max_length=100)),
                ("documento_visitante", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("aprovada", "Aprovada"),
                            ("recusada", "Recusada"),
                        ],
                        default="pendente",
                        help_text="Status da autorização",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("respondido_em", models.DateTimeField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuário da portaria que registrou a solicitação",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "respondido_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="Morador que autorizou ou recusou",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="condominios.morador",
                    ),
                ),
                (
                    "unidade_destino",
                    models.ForeignKey(
                        help_text="Unidade que o visitante quer acessar",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="condominios.unidade",
                    ),
                ),
            ],
        ),
    ]
