# Generated by Django 5.2 on 2025-04-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0020_morador_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='condominio',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='condominio',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='condominio',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
