# Generated by Django 5.2 on 2025-04-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0021_condominio_ativo_condominio_cidade_condominio_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocorrencia',
            old_name='criado_em',
            new_name='data_registro',
        ),
        migrations.RenameField(
            model_name='reservaespaco',
            old_name='data_reserva',
            new_name='data',
        ),
        migrations.AddField(
            model_name='morador',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_moradores/'),
        ),
        migrations.AddField(
            model_name='morador',
            name='is_inquilino',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='morador',
            name='is_proprietario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='morador',
            name='pode_votar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='morador',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
