# Generated by Django 5.2 on 2025-04-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("condominios", "0022_rename_criado_em_ocorrencia_data_registro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditoria",
            name="dados_anteriores",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditoria",
            name="dados_novos",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="auditoria",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="auditoria",
            name="objeto_id",
            field=models.CharField(max_length=100),
        ),
    ]
