# Generated by Django 5.2 on 2025-04-10 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0003_remove_morador_apartamento_unidade_morador_unidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='bloco',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em andamento'), ('resolvida', 'Resolvida')], default='aberta', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominios.morador')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominios.unidade')),
            ],
        ),
    ]
