# Generated by Django 5.2 on 2025-04-10 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominios', '0004_alter_unidade_bloco_ocorrencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_servico', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominios.condominio')),
            ],
        ),
    ]
