# Generated by Django 5.2 on 2025-04-10 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("condominios", "0005_prestador"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("documento", models.CharField(max_length=50)),
                ("data_visita", models.DateTimeField(auto_now_add=True)),
                (
                    "morador_responsavel",
                    models.ForeignKey(
                        help_text="Morador que autorizou a entrada",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="condominios.morador",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        help_text="Unidade que está recebendo o visitante",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="condominios.unidade",
                    ),
                ),
            ],
        ),
    ]
