# Generated by Django 5.2 on 2025-04-10 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("condominios", "0007_controleacesso"),
    ]

    operations = [
        migrations.CreateModel(
            name="Correspondencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=200)),
                ("data_recebimento", models.DateTimeField(auto_now_add=True)),
                ("data_retirada", models.DateTimeField(blank=True, null=True)),
                ("entregue_por", models.CharField(blank=True, max_length=100)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "morador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="condominios.morador",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="condominios.unidade",
                    ),
                ),
            ],
        ),
    ]
