# Generated by Django 5.2 on 2025-04-10 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("condominios", "0009_espacocomum_reservaespaco"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("regulamento", "Regulamento Interno"),
                            ("ata", "Ata de Reunião"),
                            ("edital", "Edital"),
                            ("boleto", "Boleto"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=20,
                    ),
                ),
                ("arquivo", models.FileField(upload_to="documentos/")),
                ("visivel_para_moradores", models.BooleanField(default=True)),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "condominio",
                    models.ForeignKey(
                        help_text="Condomínio ao qual o documento pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="condominios.condominio",
                    ),
                ),
                (
                    "enviado_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuário que fez o upload",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
