# Generated by Django 5.2 on 2025-04-10 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("condominios", "0011_administradorgeral"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Aviso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("mensagem", models.TextField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("expira_em", models.DateTimeField(blank=True, null=True)),
                (
                    "condominio",
                    models.ForeignKey(
                        help_text="Condomínio onde o aviso será exibido",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="condominios.condominio",
                    ),
                ),
                (
                    "publicado_por",
                    models.ForeignKey(
                        help_text="Usuário que publicou o aviso",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
