# Generated by Django 5.2 on 2025-04-11 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("condominios", "0013_manutencao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cobranca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("mensalidade", "Mensalidade"),
                            ("fundo_reserva", "Fundo de Reserva"),
                            ("extraordinaria", "Extraordinária"),
                            ("outro", "Outro"),
                        ],
                        default="mensalidade",
                        max_length=20,
                    ),
                ),
                ("descricao", models.CharField(blank=True, max_length=200)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("vencimento", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("pago", "Pago"),
                            ("atrasado", "Atrasado"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "morador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="condominios.morador",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="condominios.unidade",
                    ),
                ),
            ],
        ),
    ]
