# Generated by Django 5.2 on 2025-04-11 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("condominios", "0014_cobranca"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComprovantePagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arquivo", models.FileField(upload_to="comprovantes/")),
                ("comentario", models.TextField(blank=True)),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
                ("validado", models.BooleanField(default=False)),
                (
                    "cobranca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="condominios.cobranca",
                    ),
                ),
                (
                    "morador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="condominios.morador",
                    ),
                ),
                (
                    "validado_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuário que validou o comprovante",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comprovantes_validados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
